version: "3.8"

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  app:
    build: .
    restart: on-failure
    expose: 
      - 5000
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
      
  nginx:
    restart: always
    build: nginx
    ports:
      - 80:80
      - 443:80
    volumes:
      - ./cert:/cert
      - ./nginx:/etc/nginx/conf.d

volumes:
  db-data:
